### ISSUE TITLE
Soundcloud Links Have Problem to Play

### ISSUE THREAD

**Issue by Kazuma1234** [robinfriedli/botify#251] opened 2021-08-14 12:40 UTC
The first time I used the bot can play the music from soundcloud's links. However, after a few months later, I used the bot to play the soundcloud, and I unable to do it, but not for youtube's links.

**Comment by robinfriedli** [comment] 2021-08-14 15:04
Most likely caused by https://github.com/sedmelluq/lavaplayer/issues/651

**Comment by robinfriedli** [comment] 2021-09-21 10:22
fixed by #255

**Closed by robinfriedli** 2021-09-21 10:22 UTC
